In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.array([1.0, -2.0])
w = np.array([[0.5, -1.0, 2.0],
              [1.5,  0.0, -0.5]])
b = np.array([0.1, -0.2, 0.3])

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def relu(x):
    return np.maximum(0, x)

In [6]:
def step(x):
    return (x>0).astype(int)

In [13]:
x = x.reshape(-1,1)

In [14]:
x.shape

(2, 1)

In [15]:
sigmoid(x*w + b)

array([[0.64565631, 0.23147522, 0.90887704],
       [0.05215356, 0.450166  , 0.78583498]])

In [16]:
relu(x*w + b)

array([[0.6, 0. , 2.3],
       [0. , 0. , 1.3]])

In [17]:
step(x*w + b)

array([[1, 0, 1],
       [0, 0, 1]])

In [20]:
y_observed = [0.06, 0.8, 0.11, 0.65, 0.34, 0.5, 0.74, 0.62, 0.4]
y_predicted = [0.05, 0.9, 0.1, 0.6, 0.2, 0.8, 0.3, 0.7, 0.5]

In [21]:
def mae(y_observed, y_predicted):
    y_observed_array = np.array(y_observed)
    y_predicted_array = np.array(y_predicted)
    return np.mean((y_observed_array - y_predicted_array))

In [22]:
mae(y_observed, y_predicted)

np.float64(0.007777777777777788)

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mean_squared_error(y_observed, y_predicted)

0.03692222222222222