In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([1.0, -2.0])
w = np.array([[0.5, -1.0, 2.0],
              [1.5,  0.0, -0.5]])
b = np.array([0.1, -0.2, 0.3])

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
def relu(x):
    return np.maximum(0, x)

In [5]:
def step(x):
    return (x>0).astype(int)

In [6]:
sigmoid(x)

array([0.73105858, 0.11920292])

In [7]:
sigmoid(w)

array([[0.62245933, 0.26894142, 0.88079708],
       [0.81757448, 0.5       , 0.37754067]])

In [8]:
sigmoid(b)

array([0.52497919, 0.450166  , 0.57444252])

In [9]:
relu(x)

array([1., 0.])

In [10]:
relu(w)

array([[0.5, 0. , 2. ],
       [1.5, 0. , 0. ]])

In [11]:
relu(b)

array([0.1, 0. , 0.3])

In [12]:
step(x)

array([1, 0])

In [13]:
step(w)

array([[1, 0, 1],
       [1, 0, 0]])

In [14]:
step(b)

array([1, 0, 1])

In [15]:
y_observed = [0.06, 0.8, 0.11, 0.65, 0.34, 0.5, 0.74, 0.62, 0.4]
y_predicted = [0.05, 0.9, 0.1, 0.6, 0.2, 0.8, 0.3, 0.7, 0.5]

In [16]:
def mse(y_observed, y_predicted):
    y_observed_array = np.array(y_observed)
    y_predicted_array = np.array(y_predicted)
    return np.mean((y_observed_array - y_predicted_array)**2)

In [17]:
mse(y_observed, y_predicted)

np.float64(0.03692222222222222)

In [18]:
from sklearn.metrics import mean_squared_error

In [19]:
mean_squared_error(y_observed, y_predicted)

0.03692222222222222